import React, { useEffect, useState } from 'react';
import { Card, Loader, FormField } from '../components';
import axios from 'axios';

// const RenderCards=(data)=>{

//      if(data.length >0 ) return data.map((post)=>
//     <Card key={post._id} {...post} /> )

//      return (
//       <h2 className='mt-5 font-bold text-[#6449ff] text-xl uppercase'>
//         {title}
//       </h2>
//      )
// }

const Home = () => {

  const [loading, setLoading]= useState(false);
  const [allPosts, setAllPosts]= useState([]);
  const [searchText ,setSearchText]= useState("");
  const [searchResults, setSearchResults]= useState([]);
  const [searchTimeout, setSearchTimeout]= useState(null);
  const [tempPosts, setTempPosts]= useState([]);

  useEffect(()=>{

    const fetchPosts= async ()=>{
       setLoading(true);

       try{
          const res= await axios.get("https://imagine-ksvgudj4y-akshat-singhs-projects-5fe4f296.vercel.app/api/v1/post");
           
          
            setAllPosts(res.data.data);
            setTempPosts(res.data.data);
            console.log(allPosts);
        
       }
       catch(err){
         alert(err);
       }finally{
        setLoading(false);
       }
    }
    fetchPosts();
  },[]);
  

 
  const handleSearchChange=(e)=>{

  
    setSearchText(e.target.value);

    const searchResults= allPosts.filter((item)=>  
        item.prompt.toLowerCase().includes(searchText.toLowerCase()) || item.name.toLowerCase().includes(searchText.toLowerCase()) )
        
        setTempPosts(searchResults);
     
   }



  return (
      <section className='max-w-7xl mx-auto'>
         <div>
          <h1 className='font-extrabold text-[#222328] text-[32px]'>
            The Community Showcase
          </h1>
          <p className='mt-2 text-[#666375] text-[16px] max-w-[500px]'>
            Browse through a collection of imaginative and visually stunning images generated by ImagineAI
          </p>
         </div>
         <div className='mt-16 '>
           <FormField 
           LabelName="Search Posts"
           type="text"
           name="text"
           placeholder="Search Posts"
           value={searchText}
           handleChange={handleSearchChange}
           
            />
           
         </div>
         <div className='mt-10'>

          {/* {loading ? 
          https://imagine-jdw1d7fbr-akshat-singhs-projects-5fe4f296.vercel.app/
          (<div className='flex justify-center items-center'>
            <Loader/>
          </div>)} */}
          
          
              {/* {searchText.length > 0 && (<h2 className='font-medium text-[#666e75] text-xl mb-3'>
                Showing results for <span className='text-[#22328]'>{searchText}</span>
              </h2>
              )} */}
              <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3'>

                {/*                
                {  searchText ? (searchResults.map((post,index)=> <Card data={post} key={index}/>))
                :(allPosts.map((post)=> <Card data={post} key={post._id}/>)) 
                } */}
                {
                  tempPosts.map((post)=> <Card data= {post} key={post._id}/>)
                }

              </div>

              
              
           
           

         </div>
      </section>
  )
}

export default Home